apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: dotnet-build-autoscaler
build:
  artifacts:
    - image: backend
      context: BuildJobApi
      docker:
        dockerfile: Dockerfile
    - image: kafka-consumer
      context: KafkaConsumer
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/backend-deployment.yaml
    - kubernetes/backend-service.yaml
    - kubernetes/keda-scaled-jobs.yaml
    - kubernetes/kafdrop.yaml
deploy:
  helm:
    releases:
      - name: keda
        repo: https://kedacore.github.io/charts 
        remoteChart: keda
        namespace: keda
        createNamespace: true
      - name: kafka
        remoteChart: oci://registry-1.docker.io/bitnamicharts/kafka
        setValues:
          listeners.client.protocol: PLAINTEXT
          listeners.controller.protocol: PLAINTEXT
          listeners.interbroker.protocol: PLAINTEXT
          listeners.external.protocol: PLAINTEXT
      - name: minio
        remoteChart: oci://registry-1.docker.io/bitnamicharts/minio
        setValues:
          auth.rootPassword: password