apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_BUCKET_NAME
              value: job-requests
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: MINIO_SECRET_KEY
              value: password
          image: backend
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
